# fly.toml app configuration file generated for ayusin-fe on 2025-09-21T15:07:31+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ayusin-fe'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
